### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by karelin** [BOHRTECHNOLOGY/quantum_tsp#5]
The link to demo notebook (see end of README file) goes to 404 page

**Comment by perak** [comment]
@karelin thank you for reporting. 

Correct link is https://nbviewer.jupyter.org/github/Qiskit/qiskit-tutorial/blob/master/qiskit/aqua/optimization/maxcut_and_tsp.ipynb

README.md will be updated soon.

👍

**Comment by mstechly** [comment]
@karelin Thanks for pointing it out, they updated this tutorial in the meantime :)
