### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by AndyWZJ** [BOHRTECHNOLOGY/quantum_tsp#7]
I have run the TSP demo, but the nodes of TSP more than about 10 could not get the result and 
return a “ValueError: no embedding found” error in Python. After many times tests for this demo using
 D-Wave, the results of TSP with 5 to 10 nodes were apparently wrong. I did not test in the Forest.

       So if you have any great solutions about this problem, please tell me how you solved it. 
       Many thanks in advance.

**Comment by mstechly** [comment]
Hi! It's not possible to solve problems of size 10 or more using D-Wave 2000Q, since this problem is too big to fit onto the QPU. Perhaps there exists an embedding, that you can find using minorminer, but I've never suceeded.
